PRAGMA foreign_keys=ON

CREATE TABLE SCHEMA_VERSION (
    VERSION INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    HOST TEXT NOT NULL,
    PORT INTEGER NOT NULL,
    DATABASE TEXT NOT NULL,
    TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE SCHEMA_INDEX (
    VERSION INTEGER NOT NULL,
    INDEX_SCHEMA TEXT NOT NULL,
    TABLE_NAME TEXT NOT NULL,
    INDEX_NAME TEXT NOT NULL,
    INDEX_COLUMNS TEXT NOT NULL,
    INDEX_TYPE TEXT NOT NULL,
    IS_UNIQUE INTEGER NOT NULL,
    TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_SCHEMA_INDEX_SCHEMA_VERSION FOREIGN KEY (VERSION) REFERENCES SCHEMA_VERSION (VERSION) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SCHEMA_FOREIGN_KEY (
    VERSION INTEGER NOT NULL,
    TABLE_SCHEMA TEXT NOT NULL,
    TABLE_NAME TEXT NOT NULL,
    CONSTRAINT_NAME TEXT NOT NULL,
    COLUMN_NAMES TEXT NOT NULL,
    REFERENCED_TABLE_NAME TEXT NOT NULL,
    REFERENCED_COLUMN_NAMES TEXT NOT NULL,
    TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_SCHEMA_INDEX_SCHEMA_VERSION FOREIGN KEY (VERSION) REFERENCES SCHEMA_VERSION (VERSION) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SCHEMA_TABLE (
    VERSION INTEGER NOT NULL,
    TABLE_SCHEMA TEXT NOT NULL,
    TABLE_NAME TEXT NOT NULL,
    ENGINE TEXT NOT NULL,
    ROW_FORMAT TEXT NOT NULL,
    TABLE_ROWS INTEGER NOT NULL,
    DATA_LENGTH INTEGER NOT NULL,
    INDEX_LENGTH INTEGER NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP NULL,
    TABLE_COLLATION TEXT NOT NULL,
    TABLE_COMMENT TEXT NOT NULL,
    TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_SCHEMA_INDEX_SCHEMA_VERSION FOREIGN KEY (VERSION) REFERENCES SCHEMA_VERSION (VERSION) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SCHEMA_COLUMN (
    VERSION INTEGER NOT NULL,
    TABLE_SCHEMA TEXT NOT NULL,
    TABLE_NAME TEXT NOT NULL,
    COLUMN_NAME TEXT NOT NULL,
    ORDINAL_POSITION INTEGER NOT NULL,
    COLUMN_DEFAULT TEXT NULL,
    IS_NULLABLE TEXT NOT NULL,
    DATA_TYPE TEXT NOT NULL,
    CHARACTER_MAXIMUM_LENGTH INTEGER NULL,
    NUMERIC_PRECISION INTEGER NULL ,
    NUMERIC_SCALE INTEGER NULL,
    COLLATION_NAME TEXT NULL,
    COLUMN_TYPE TEXT NOT NULL,
    COLUMN_COMMENT TEXT NOT NULL,
    GENERATION_EXPRESSION TEXT NOT NULL,
    TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_SCHEMA_INDEX_SCHEMA_VERSION FOREIGN KEY (VERSION) REFERENCES SCHEMA_VERSION (VERSION) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SCHEMA_VIEW (
    VERSION INTEGER NOT NULL,
    TABLE_SCHEMA TEXT NOT NULL,
    TABLE_NAME TEXT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP NULL,
    VIEW_DEFINITION TEXT NOT NULL,
    CHECK_OPTION TEXT NOT NULL,
    IS_UPDATABLE TEXT NOT NULL,
    DEFINER TEXT NOT NULL,
    COLLATION_CONNECTION TEXT NOT NULL,
    TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_SCHEMA_INDEX_SCHEMA_VERSION FOREIGN KEY (VERSION) REFERENCES SCHEMA_VERSION (VERSION) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SCHEMA_ROUTINE (
    VERSION INTEGER NOT NULL,
    ROUTINE_SCHEMA TEXT NOT NULL,
    ROUTINE_NAME TEXT NOT NULL,
    ROUTINE_TYPE TEXT NOT NULL,
    COLLATION_NAME TEXT NULL,
    ROUTINE_DEFINITION TEXT NULL,
    CREATED TIMESTAMP NOT NULL,
    LAST_ALTERED TIMESTAMP NOT NULL,
    DEFINER TEXT NOT NULL,
    TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_SCHEMA_INDEX_SCHEMA_VERSION FOREIGN KEY (VERSION) REFERENCES SCHEMA_VERSION (VERSION) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PROCESS_WATCH (
    SEQ INTEGER PRIMARY KEY AUTOINCREMENT,
    ID INTEGER NOT NULL,
    USER TEXT NOT NULL,
    HOST TEXT NOT NULL,
    DB TEXT NOT NULL,
    COMMAND TEXT NOT NULL,
    TIME INTEGER NOT NULL,
    STATE TEXT NULL,
    INFO TEXT NULL,
    INSERT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

/*
SELECT * FROM SCHEMA_VERSION ORDER BY time DESC
SELECT * FROM SCHEMA_INDEX ORDER BY time DESC
SELECT * FROM SCHEMA_FOREIGN_KEY ORDER BY time DESC
SELECT * FROM SCHEMA_TABLE ORDER BY time DESC
SELECT * FROM SCHEMA_COLUMN ORDER BY time DESC
SELECT * FROM SCHEMA_VIEW ORDER BY time DESC
SELECT * FROM SCHEMA_ROUTINE ORDER BY time desc
SELECT DISTINCT table_schema FROM SCHEMA_TABLE
*/

/*
DELETE FROM SCHEMA_VERSION where version >= 43;
DELETE FROM SCHEMA_INDEX where version not in (select version from schema_version);
DELETE FROM SCHEMA_FOREIGN_KEY where version not in (select version from schema_version);
DELETE FROM SCHEMA_TABLE where version not in (select version from schema_version);
DELETE FROM SCHEMA_COLUMN where version not in (select version from schema_version);
DELETE FROM SCHEMA_VIEW where version not in (select version from schema_version);
DELETE FROM SCHEMA_ROUTINE where version not in (select version from schema_version);

DROP TABLE SCHEMA_VERSION;
DROP TABLE SCHEMA_INDEX;
DROP TABLE SCHEMA_FOREIGN_KEY;
DROP TABLE SCHEMA_TABLE;
DROP TABLE SCHEMA_COLUMN;
DROP TABLE SCHEMA_VIEW;
DROP TABLE SCHEMA_ROUTINE;
*/
